# Generated by Django 5.0.8 on 2024-09-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Pasteleria', 'Pasteleria'), ('Bebidas', 'bebidas')], max_length=40),
        ),
    ]
