# Generated by Django 5.0.8 on 2024-09-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
