# Generated by Django 5.0.8 on 2024-09-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0008_alter_comentario_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='user',
        ),
    ]
